services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"

    volumes:
      - .:/app

  db:
    image: postgres:17

    environment:
      POSTGRES_DB: focusflow_db
      POSTGRES_USER: focusflow_user
      POSTGRES_PASSWORD: focusflow_password

    ports:
      - "5432:5432"