# Generated by Django 6.0.6 on 2026-06-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productivity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="goal_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="target_date",
            field=models.DateField(db_index=True),
        ),
    ]
