# Generated by Django 6.0.6 on 2026-06-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productivity", "0002_alter_goal_goal_date_alter_goal_target_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="streak",
            old_name="last_completion_date",
            new_name="last_streak_update",
        ),
    ]
