# Generated by Django 6.0.6 on 2026-06-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productivity", "0003_rename_last_completion_date_streak_last_streak_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="streak",
            options={"verbose_name": "Streak", "verbose_name_plural": "Streaks"},
        ),
        migrations.RenameField(
            model_name="streak",
            old_name="last_streak_update",
            new_name="last_evaluated_date",
        ),
    ]
