# Generated by Django 6.0.6 on 2026-06-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productivity", "0004_alter_streak_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="focussession",
            name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="target_date",
        ),
    ]
