# Generated by Django 6.0.6 on 2026-08-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productivity", "0005_remove_focussession_duration_minutes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="goal_date",
            new_name="target_date",
        ),
        migrations.AddField(
            model_name="goal",
            name="category",
            field=models.CharField(
                choices=[
                    ("CAREER", "Career"),
                    ("LEARNING", "Learning"),
                    ("HEALTH", "Health"),
                    ("FINANCE", "Finance"),
                    ("PERSONAL", "Personal"),
                ],
                default="PERSONAL",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="progress",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="goal",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
    ]
